services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      - ../src:/app/src
      - ../pom.xml:/app/pom.xml
      - ~/.m2:/root/.m2
    command: sh -c "mvn spring-boot:run -Dspring-boot.run.profiles=dev"
    ports:
      - "${SPRING_APP_PORT:-8080}:8080"
      - "5005:5005"
    networks:
      - project_network
